name: Test-Build
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make Directory for results
        run: mkdir -p testResults

      - name: Run POSTMAN collection
        run: |
          newman run petstore.collection.json \
            -r htmlextra \
            --reporter-htmlextra-export testResults/htmlreport.html \
            --reporter-htmlextra-darkTheme \
            || true

      - name: Output the run Details
        uses: actions/upload-artifact@v3
        with:
          name: RunReports
          path: testResults 

      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: RunReports

      - name: Copy the HTML report to the root
        run: |
          cp testResults/htmlreport.html ./htmlreport.html
          cp testResults/htmlreport.html ./index.html

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./  # Publish from the root directory
